### ISSUE TITLE
About Text's fontSize

### ISSUE THREAD

**Issue by odarino** [invertase/react-native-apple-authentication#104]
Hi, 

I have question, is there any way to change the fontSize of Text. It seems quite big. 

It would be great if having any. 

Thank you

**Comment by mikehardy** [comment]
Apple has strict design criteria and generates the UI element directly.
You are quite specifically not allowed any control over the element except a little rounding.
That's Apple :-)

**Comment by nes123** [comment]
If I will create my button they will reject it in review?

**Comment by mikehardy** [comment]
You can't seriously be asking some random developer on the internet what some random approver in the Apple App review process will do, can you? I don't say that to be mean *at all*, just the Apple Review process is so unpredictable. Who knows? They might reject your perfect implementation one time because of a network problem then approve the exact same code the next time. Or the opposite. Who knows

But I would not mess with their buttons.
The only thing I do with the button is overlay a loading indicator on it to indicate we are processing after click.

**Comment by nes123** [comment]
Actually i read in their website and it is completely fine to change the font and size..

**Comment by mikehardy** [comment]
That's new to me, can you paste a link in here? It is always possible I misunderstand

**Comment by nes123** [comment]
https://developer.apple.com/design/human-interface-guidelines/sign-in-with-apple/overview/buttons/

"Use the system font for the title — that is, Sign in with Apple, Sign up with Apple, or Continue with Apple. To look correct, the title and button height of your custom button should use the same proportions that the system uses. Specifically, the title's font size should be 43% of the button's height — in other words, the button's height should be 233% of the title's font size, rounded to the nearest integer. Here are two examples that illustrate these proportions."

I didnt see any constraint on the font.

**Comment by loopbender** [comment]
Thanks heaps for the amazing library, however +1 for changing font size props

**Comment by mikehardy** [comment]
I suppose we could take a PR that would allow taking a font size prop if their *provided APIs for getting the provided buttons* allow that, otherwise, I think the point of the link posted above is that you can create a custom button as long as you follow their guidelines - given this is a react-native library I think that means you'd just do typical button / pressable styling at the javascript layer and there's nothing module-specific about it?

**Comment by loopbender** [comment]
oh I see now that you are using the native provided one, so indeed providing a customizable button is a little out of scope of this module.

additionally, reading the paragraph with full attention now, I don't think we can change the font size anyways. because it is specifically said to be the 43% of the button's height, which is the case with the button already...

thank you for the library again
