### ISSUE TITLE
Add tvOS support

### ISSUE THREAD

**Issue by ruen89** [invertase/react-native-apple-authentication#120]
Hi,

Would it be possible to add tvOS support for this library?
I'm currently working on a project react-native tvOS project that would benefit a lot from it

**Comment by mikehardy** [comment]
Sure, looks like it's supported on tvOS13+ per upstream docs https://developer.apple.com/documentation/authenticationservices

Is there anything special that needs to be done, separate from iOS? The API calls should be the same, so it seems like it should "Just Work".

If not, PRs to make it work could be merged, sure

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
