### ISSUE TITLE
Apple rejection

### ISSUE THREAD

**Issue by danielmorbeck** [invertase/react-native-apple-authentication#125]
When trying to publish my app I get the following rejection message from Apple:

"We discovered one or more bugs in your app when reviewed on iPad running iOS 13.6 on Wi-Fi.

Specifically, we were still unable to sign in with Apple."

Everything seems to work fine on other devices. Since I don't have an iPad running iOS 13.6, I'm unable to test it.

Anyone having this issue?

**Comment by mikehardy** [comment]
I think there are examples in the closed issues list. It works AFAIK but the reviewers themselves had network issues if I recall correctly

**Comment by danielmorbeck** [comment]
@mikehardy that's unfortunate, we tried on an iPad with different networks config, but still we're unable to reproduce the problem they are having.

**Comment by stefanholzapfel** [comment]
Our app is also rejected since integrating the authentication package (no other chagnes), but with a different message:

We discovered one or more bugs in your app when reviewed on iPad running iOS 13.6.1 on Wi-Fi.
Specifically, your app did not load beyond the splash screen.

I have no iPad and can't reproduce the issue on Simulator and iPhone.

**Comment by mikehardy** [comment]
This happens sometimes but we also have lots and lots of users succeeding. For some reason on the App reviewer's devices it fails some times but it is out of our control here, sorry

**Comment by stefanholzapfel** [comment]
true, apple is out of control atm :)

**Comment by danielmorbeck** [comment]
Update:
 It turned out that the problem wasn't with apple sign in, but with our authentication on back-end.
