### ISSUE TITLE
ReferenceError: Can't find variable: AppleButton

### ISSUE THREAD

**Issue by magickasoft** [invertase/react-native-apple-authentication#150]
please correct the export function in `lib/AppleButton.android.js` line 10
change to
`export default function AppleButton(props) {`
<img width="840" alt="Снимок экрана 2020-10-12 в 03 46 41" src="https://user-images.githubusercontent.com/16606738/95690093-6f04f180-0c3f-11eb-9375-5a974ec56fbd.png">

**Comment by mikehardy** [comment]
Please explain how it works in the example but still needs a change?

https://github.com/invertase/react-native-apple-authentication/blob/master/example/app.ios.js#L21

I need to see a reproduction of some actual problem, note that a reproduction involves no images - screenshots are not useful - I need to see a project based on `react-native init` followed by adding react-native-apple-authentication and then a self-contained App.js that has the problem

**Comment by LRNZ09** [comment]
I got the same issue when using the latest version, `2.0.2`

**Comment by magickasoft** [comment]
@mikehardy, I suggested a fix for this problem (I think there will be more than one person who will have this problem), please add the fix described above, if your bug does not reproduce, this does not mean that it is not there, we are waiting for a fresh release of the package with correction, thanks

**Comment by mikehardy** [comment]
@magickasoft I asked for help understanding the problem, and a reproduction - this is to make sure that it doesn't exist in other parts of the module and so I/we can put something in the example that will make sure it doesn't happen again.

I don't accept changes simply because people insist. I believe there is a problem and I'd like to fix it but I'd appreciate your help with the above

**Comment by magickasoft** [comment]
@mikehardy updated the project to `"react-native": "0.63.3",` the error disappeared. An error appeared on the template `"react-native": "0.61.5",`

**Comment by mikehardy** [comment]
Interesting - glad to hear your project is moving forward but it sounds like we may have had an unexpected breaking change based on expectation of some transitive dependency behaving in a certain way, that changed between RN0.61.5 and RN0.63.3, I'll keep this open in case I/we can isolate it and either note it or handle it correctly once we figure out exactly what happened

**Comment by mikehardy** [comment]
I just noticed that the example app is actually against RN61 still, so there is no breaking change that I'm aware of

**Comment by JasonTolliver** [comment]
FWIW, I'm seeing the same exact issue

```
"@invertase/react-native-apple-authentication": "^2.1.0",
"react-native": "0.63.2",
```

I am only able to fix by applying @magickasoft's initial suggested change to the source...

**Comment by mikehardy** [comment]
If you can reproduce it with the example app we can troubleshoot and fix otherwise...what can we do?

**Comment by JasonTolliver** [comment]
@mikehardy, happy to give it a shot.  I didn't spot any contribution guide offhand.  Is there a quick spot to find out to test against the example app?

It's worth noting that this is the only file in the JS that uses an arrow function.  I suspect that the issue has something with this package expecting the bundler to transpile, while some setting in the bundler (be it the newest version of RN or some custom setting of our own) is expecting all packages to already be transpiled.  (Really a wild shot in the dark since it would be shocking to me to find out that the JS engines on Android wouldn't natively support arrow functions.  Perhaps it's even just the simulator?)

**Comment by mikehardy** [comment]
I dunno. Just pull the repo, yarn in the example, yarn in the man and run yarn dev-sync to get changes into node_modules in the example repeat as needed

**Comment by bulgr0z** [comment]
We encountered this problem too; it was caused by `@babel/preset-env`. Disabling the preset (or in our case only including it in the `test` env) fixes the error.

I did not find the time to investigate it further yet, but it might help some folks and prevent them from manually patching the lib.

**Comment by EIrwin** [comment]
I have posted a [PR](https://github.com/invertase/react-native-apple-authentication/pull/234) with the change to make this not use an arrow function.  

I have not come across another method for fixing this unfortunately, and this appears to be a safe change.

**Comment by mikehardy** [comment]
@EIrwin for the win :trophy: 

https://github.com/invertase/react-native-apple-authentication/releases/tag/v2.1.4
