### ISSUE TITLE
Auth sheet is not Open 

### ISSUE THREAD

**Issue by Osamasomy** [invertase/react-native-apple-authentication#152]
<img width="281" alt="Screenshot 2020-10-16 at 23 56 23" src="https://user-images.githubusercontent.com/29625742/96298077-49933180-100b-11eb-949d-5850bd284fa8.png">

trying to implement the Apple Auth in the app. after some changes Auth sheed is no more Open. I want to get user Email id.

**Comment by mikehardy** [comment]
You get one chance I believe. It is an API thing, just part of how Apple designed their flow. If you want to see it again during development you need to go into your phone settings, passwords and security, apps using apple id, and disconnect the app

I don't think there is anything this module can do, so I will close this, but it's a common confusion because Apple is different then the others. I believe if you must, it is possible to decode the email from the token - there are other issues in the tracker that even have example code on how to do this
