### ISSUE TITLE
Ander RN 0.60 compatibility problem

### ISSUE THREAD

**Issue by azzaGarsaa** [invertase/react-native-apple-authentication#154]
Hello everyone, 
would it be possible to get it working with react 0.58.5 ? 
I am currently working on an existing project that the owner does not want to upgrade, and Apple refuses to publish to app without Apple auth

**Comment by mikehardy** [comment]
Apple will refuse to publish the app if you build it with old xcode or don't support ios14 too ?
Either way, there is not likely to be any official support here but it is open source, if you can figure out how to link it etc
With no intention of being rude - I have been a consultant and contractor all through my life - this seems like a time to tell the client that they have to do this eventually in order to support android 10/11 and ios 13/14. There is no escaping it forever. And this is a great time to do it.

https://react-native-community.github.io/upgrade-helper/ should help a great deal, it's only the leap from 59 to 60 that is hard. but if you do each version one at a time it should not be too hard to get to 60 (and then you basically have 0.63.x for free - all the steps from 60 to 63 are pretty easy too)

To be clear though - this library does not official support rn59 or lower, and we won't merge support for it, with apologies
