### ISSUE TITLE
Apple login page crashes and goes back the app login screen

### ISSUE THREAD

**Issue by Decoder3-14** [invertase/react-native-apple-authentication#170]
I am implementing this library on an android device, and although I am using the right credentials and all, I am getting a weird error that I did not find a related issue in the issues section.
The error body literally just says the following:

`Possible Unhandled Promise Rejection (id: 0):
Error: E_SIGNIN_CANCELLED_ERROR
Error: E_SIGNIN_CANCELLED_ERROR`

Any ideas why I am getting this error and how to resolve it?
All thoughts are appreciated

**Comment by mikehardy** [comment]
Your code has an error, you are not calling things in a try/catch and using promises correctly, so you are seeing an error bubble up to a full app crash

The "error" is that the user cancelled, and you need to handle that

This does not appear like a problem with the module

**Comment by shllg** [comment]
Hi @mikehardy ,

Of course, errors need to be handled. The issue here is (I guess) not the handling after the crash.

Running `await appleAuthAndroid.signIn()` will always open and directly close a window. The result is `E_SIGNIN_CANCELLED_ERROR`. I tried different configurations. The `clientId` and `redirectUrl` I'm using work fine at the web setup.

I tried to get more insights via logcat. But there are no errors or similar between the JS execution and error catch.  

You can find the output here:
https://gist.github.com/shllg/5417acdfc8c878794cc881b2ac7db168

Any ideas?

**Comment by mikehardy** [comment]
Best idea is always to suppy minimal reproducible example https://stackoverflow.com/help/minimal-reproducible-example which for our purposes is a self-contained App.js that shows a deviation from the API contracts the module provides
