### ISSUE TITLE
iOS Androind different cancel code

### ISSUE THREAD

**Issue by Romick2005** [invertase/react-native-apple-authentication#175]
When I add apple android login my app start log cancel auth error - 'E_SIGNIN_CANCELLED_ERROR'.
That is because iOS and Android send different errors.
iOS errors:
```
Error = {
  UNKNOWN: '1000',
  CANCELED: '1001',
  INVALID_RESPONSE: '1002',
  NOT_HANDLED: '1003',
  FAILED: '1004',
};
```

Android errors:
```
private static final String E_NOT_CONFIGURED_ERROR = "E_NOT_CONFIGURED_ERROR";
private static final String E_SIGNIN_FAILED_ERROR = "E_SIGNIN_FAILED_ERROR";
private static final String E_SIGNIN_CANCELLED_ERROR = "E_SIGNIN_CANCELLED_ERROR";
...
Error: {
  NOT_CONFIGURED: RNAppleAuthModuleAndroid.E_NOT_CONFIGURED_ERROR,
  SIGNIN_FAILED: RNAppleAuthModuleAndroid.E_SIGNIN_FAILED_ERROR,
  SIGNIN_CANCELLED: RNAppleAuthModuleAndroid.E_SIGNIN_CANCELLED_ERROR,
}
```
I would suggest to have same error codes to avoid confusion.

So to deal with both error I have to change my code and now it looks like:
```
// Do not show error if user canceled login
// Error code 1001 - The user canceled the authorization attempt.
if (
  error.code !== appleAuth.Error.CANCELED && 
  error.message !== appleAuthAndroid.Error.SIGNIN_CANCELLED
) {
  me.showFailedLoginMessage(error, "apple");
}
```
Would be good if Android error and iOS error would have at least same code

**Comment by mikehardy** [comment]
If you post a PR implementing this idea I could merge it

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
