### ISSUE TITLE
iOS 14: auth user displayName is not set

### ISSUE THREAD

**Issue by muchai-mercy** [invertase/react-native-apple-authentication#198]
Hi,

I am using this library in the latest version: `2.1.1`.

I am setting the user displayName from the `appleAuthRequestResponse` fullName. For iOS 14, the displayName is not set.
On iOS 13, it works. I am able to access the displayName as expected. 

Steps to reproduce:
Real Device iOS version: 14.4
When I sign up with apple I expect to see a displayName when I update the user profile.
Result: The displayName is not being set.

Testing on simulator iOS 13.2, I see the displayName.

**Comment by mikehardy** [comment]
I don't believe Apple APIs guarantee you will always receive that value. Similar to email I believe you may only receive that the first time you ever authenticate with a user, then after that you must rely on stored data. Also the user may elect to not share it. I don't believe there is anything actionable this package can do.

**Comment by muchai-mercy** [comment]
True, the apple API does not guarantee receiving the value and access depends on what the user chooses to share.

However, as a user, given I chose to share the email data, testing on the different iOS versions has different results. For iOS 13, I always receive the value. For iOS 14,(same apple ID, same access) I do not receive the value. Is that beyond the scope of this package?

> I don't believe Apple APIs guarantee you will always receive that value. Similar to email I believe you may only receive that the first time you ever authenticate with a user, then after that you must rely on stored data. Also the user may elect to not share it. I don't believe there is anything actionable this package can do.

**Comment by mikehardy** [comment]
If you can point to some way we are using the APIs incorrectly, then it is in the scope of the package

If it is the APIs just behaving differently because Apple chooses to return different things at different times in ways that developers don't expect, that's an Apple thing

One thing that confuses people a lot in initial integrations of this package is how to fully reset the state of your app and the apple authentication with respect to your user id, for testing. It may just be that your state is not fully reset the way you think it is, so you are not actually testing "first login ever by a user" on iOS14, giving different results from iOS13 but only because the app is already associated / not completely disassociated. Other than that, I can't think of anything.

I'll re-open this no problem if you can point to an API we're using incorrectly, but otherwise I really don't think this is actionable in this package
