### ISSUE TITLE
Android - begin load white screen

### ISSUE THREAD

**Issue by mboworldbest** [invertase/react-native-apple-authentication#215]
-  When i call appleAuthAndroid.signIn(), begin white screen in 3 senconds.

![begin_white_screen](https://user-images.githubusercontent.com/63733745/123033338-ce8fdf80-d411-11eb-863d-496dbb1c715e.png)

**I want implement show loading while white screen.
How to implement show loading?**

- After normal

![after_ordinary](https://user-images.githubusercontent.com/63733745/123033741-71485e00-d412-11eb-80eb-2c5df704b9fc.png)

i use version
**"react-native": "0.63.4"
"@invertase/react-native-apple-authentication": "2.1.2"**

**Comment by Romick2005** [comment]
As a workaround, you can check my [fork](https://github.com/invertase/react-native-apple-authentication/pull/177#issuecomment-798991595)

**Comment by mikehardy** [comment]
@Romick2005 that's a great suggestion, and @mboworldbest *if* I am understanding your request, which I would restate as "I would like to provide a loading indicator while waiting for the Apple auth stuff to render" (is that right?) - then using a WebView based solution means you may provide a loading indicator as shown in an example code comment from @Romick2005 

If you tried this it would serve two purposes: 1) you would have what you want 2) we would have a further success report of @Romick2005's work, which I sadly have not reviewed and merged yet, but I would like to merge as it seems greata

**Comment by Romick2005** [comment]
Hi @mboworldbest is there any success?

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality / clarify documentation but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
