### ISSUE TITLE
How to remove id from Apple account from here Stop using apple id

### ISSUE THREAD

**Issue by puneetkansal04** [invertase/react-native-apple-authentication#222]
As I am using this manually then login works fine.

To remove app, Go to settings > Profile > Password & Security > Apps using apple id > Your App > Stop using apple id

Other wise it is stop working.

Hi @mikehardy Please check it let me know what is wrong in this. How can I do login even id is added in this location.

**Comment by mikehardy** [comment]
This is not a bug in the module. The Apple sign in just functions strangely. That's Apple.

**Comment by puneetkansal04** [comment]
> This is not a bug in the module. The Apple sign in just functions strangely. That's Apple.

That's I Understand @mikehardy I am not saying this is a bug. But how can we resolve. As it does like this then 2nd time login will not work. What solution can we use here.

**Comment by mikehardy** [comment]
There's no problem I see.
You haven't specified a set of steps that fail when you expect them so I don't know what your problem is.
Apple Sign-in provides you with the information about the user **once and only once**.
You store that on your back end for future logins to match with whatever token apple gives you on future logins.

If the user deletes their account from your app, but does not clear your app from their apple sign-in allowed apps, then you will be out of sync and a future login via apple sign in may result in you not recognizing the user since you are out of sync. **you have to handle that**. There are issues related to that in the issues list, find them and read

If the user deletes your app from their apple sign in settings but does not delete their account from your app you will also be out of sync and need to handle it.

Read older issues. Try the example app. Experiment with your app. Handle the edge cases. Submit the build to Apple and move on - there are lots of people using this, we know it works but I can't solve all project-specific issues with usage patterns sorry

**Comment by puneetkansal04** [comment]
I was using this As per the documentation I think this helps


const onAppleLogin = async () => {
    const appleAuthRequestResponse = await appleAuth.performRequest({
      requestedOperation: appleAuth.Operation.LOGIN,
      requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
    }).catch((err) => {
      console.log('errr', err)
    })
    if (appleAuthRequestResponse.email) {
      const data = {
        email: appleAuthRequestResponse.email,
        provider_id: appleAuthRequestResponse.identityToken,
        provider: 'apple',
        name: appleAuthRequestResponse.fullName.givenName+" "+appleAuthRequestResponse.fullName.familyName,
      }
    }
  }

**Comment by mikehardy** [comment]
With apologies I have been as thorough as I can be in my responses. I will not pursue this further.
