### ISSUE TITLE
Android Login With Apple alway white screen

### ISSUE THREAD

**Issue by nguyenthanhtruongntt85** [invertase/react-native-apple-authentication#239]
Step
1. Call appleAuthAndroid.signIn()
2. Click 'See how your data is managed...'
2. Back
3. Call appleAuthAndroid.signIn()

Result: always white screen.
How to fix?
using "@invertase/react-native-apple-authentication": "2.1.5"
Thanks!

**Comment by Romick2005** [comment]
Can you please check #215?

**Comment by nguyenthanhtruongntt85** [comment]
> Can you please check #215?

case #215 is work best.
but case Click 'See how your data is managed...' and back then bug.

**Comment by nguyenthanhtruongntt85** [comment]
> Can you please check #215?
I fixed in file SignInWebViewDialogFragment.kt
    val webView = WebView(requireContext()).apply {
      settings.apply {
        javaScriptEnabled = true
        javaScriptCanOpenWindowsAutomatically = true
      }
    }

    //Ref: https://stackoverflow.com/questions/5822256/error-web-console-uncaught-typeerror-cannot-call-method-getitem-of-null-at-h
    //Begin fix
    val settings: WebSettings = webView.settings
    settings.setDomStorageEnabled(true)
    //End fix
    
why not support show loading first?

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality / clarify documentation but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
