### ISSUE TITLE
Build failed in android devices after installation

### ISSUE THREAD

**Issue by thingsbrain-joonho** [invertase/react-native-apple-authentication#246]
**Problem**
After installation, build failed in android devices with the error message below.

![Screenshot_20211118-150129](https://user-images.githubusercontent.com/54837645/142361892-c79dbfc0-e52b-4cf9-967c-1686dc624622.jpg)

"react-native": "^0.63.4",
"@invertase/react-native-apple-authentication": "^2.1.5",

**Steps**
1. yarn add @invertase/react-native-apple-authentication
2. react-native run-android
 

Your kind advices would be appreciated.

**Comment by mikehardy** [comment]
Oh no - thanks for letting us know, I was planning on taking a spin through this repo on the android side today anyway, I'll see if I can get it to go

**Comment by mikehardy** [comment]
Okay, so there is some other dependency that's depending on outdated lifecycle libraries I believe, if you do a web search you'll see that come up a lot for this problem.

This module does not have a problem unless you can show otherwise with a minimal reproducible example

I have done this and it works fine:

```bash
npx react-native init RNAppleAuthRepro
cd RNAppleAuthRepro
yarn add @invertase/react-native-apple-authentication
yarn android                 
```
