### ISSUE TITLE
Login with Android is working for debug but silently failing for release.

### ISSUE THREAD

**Issue by osielmesa** [invertase/react-native-apple-authentication#249]
The login is working in debug mode but in release mode the login page is not shown at all.

**Comment by mikehardy** [comment]
Hi there! There's no information to go on here https://stackoverflow.com/help/minimal-reproducible-example
Typically differences between release and debug are related to configuration or android minification
No one else has reported this though, and it would certainly be a showstopper so I would check your project, then check your project again, to focus effort on likely location of error

**Comment by osielmesa** [comment]
Thanks @mikehardy for your quick response. I found the issue. It was uuid silently failing when apk was generated and installed (even debug apk). I tracked the error using Alerts and the execution never passed these lines:
```
const rawNonce = uuid();
const state = uuid();
```

I just change `uuid` usage for `react-native-uuid` and everything works like a charm:
`import uuid from 'react-native-uuid';`

```
const rawNonce = uuid.v4();
const state = uuid.v4();
```

**Comment by mikehardy** [comment]
Interesting - uuid is our recommended install, so this may affect others. Curious what the root cause on that was: https://github.com/invertase/react-native-apple-authentication#2-implement-the-login-process-1

adb logcat may have useful information and it may still be related to minification

I use them successfully in android release mode:

```
mike@osxvm-little:~/work/Kullki/ksocialscore/packages/public-app (p2p-features) % cat package.json |grep uuid
    "@types/uuid": "^8.3.3",
    "uuid": "^8.3.2",
mike@osxvm-little:~/work/Kullki/ksocialscore/packages/public-app (p2p-features) % cat package.json |grep random
    "react-native-get-random-values": "^1.7.1",
```

react-native-get-random-values is imported at start of first file before app load, in order to inject a secure random generator.
