### ISSUE TITLE
AndroidError is not exported in version 2.1.5

### ISSUE THREAD

**Issue by hramli** [invertase/react-native-apple-authentication#258]
On the repo, AndroidError is exported here in [index.d.ts](https://github.com/invertase/react-native-apple-authentication/blob/main/lib/index.d.ts#L486).

However, in version 2.1.5 AndroidError is not exported:
```
/** Android */

type AndroidError = {
...
}
```

I checked the source code by downloading the zip from github itself and AndroidError is not exported there. Is this intentional? Need AndroidError for type casting during error handling.

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality / clarify documentation but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
