### ISSUE TITLE
In which moment should i use the KEY generated in apple developer portal?

### ISSUE THREAD

**Issue by jose920405** [invertase/react-native-apple-authentication#26]
Based on [this setup](https://github.com/invertase/react-native-apple-authentication/blob/master/docs/INITIAL_SETUP.md)

I have my `AuthKey` file but im not sure about how to use it and for that thing i need that.

**Comment by mikehardy** [comment]
That's a good question actually - according to [this firebase doc](https://firebase.google.com/docs/auth/ios/apple?authuser=0#enable-apple-as-a-sign-in-provider) I *think* if it is only for an iOS app, you don't need it.

And since all the react-native implementations I'm aware of are still iOS only I think that means you really don't need it.

But if you did, you'd be putting it in the firebase apple authentication configuration section in the firebase console in the Oauth code flow configuration marked optional. For what it's worth, I went ahead and configured it for my app but I'm probably more of a completionist than most

Hope this helps

**Comment by mikehardy** [comment]
y bienvenidos desde ecuador ;-)
