### ISSUE TITLE
Is Android token refresh supported?

### ISSUE THREAD

**Issue by Baer05** [invertase/react-native-apple-authentication#262]
Is it possible to have a permanent login on android? Under iOS you can do a refresh `appleAuthRequestResponse = await appleAuth.performRequest({
            requestedOperation: appleAuth.Operation.REFRESH,
            requestedScopes: [appleAuth.Scope.EMAIL, appleAuth.Scope.FULL_NAME],
          });` and then get a current id_token. Is this also possible on Android?

**Comment by mikehardy** [comment]
Hi there, it does not appear so.
It looks like sign-in is implemented, to retrieve the authentication token, but the rest of this document - discussing the refresh token endpoints etc - does not seem to be implemented in my scan of the Kotlin code here

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user

I have not tried this use case myself, `@react-native-firebase/auth` uses the initial apple auth token in order to obtain firebase auth tokens which firebase of course handles internally, and that's been good enough for me. I recognize that's only one use of apple auth, just explaining why I personally have never worked through refresh vs sign in with apple APIs directly.

If there's an API that this module could provide to make it easier I'd happily collaborate with you to merge any PR you posted

**Comment by mikehardy** [comment]
Happy to take PRs to resolve issues / extend functionality but as current maintainer the library currently handles my use cases, which means I do not have an interest in volunteering unpaid labor myself for use cases I don't need.

Happy to take those PRs and merge them though if anyone paying attention to this issue is motivated to develop them.

In the meantime closing this as stale
