### ISSUE TITLE
Not able to build in android 

### ISSUE THREAD

**Issue by ForamPattha** [invertase/react-native-apple-authentication#297]
![Screenshot 2022-08-18 at 3 55 28 PM](https://user-images.githubusercontent.com/66566727/185373357-98f40a1d-94d9-4b88-97fa-8cf3fce2d9c0.png)

Facing above error when build in android. Try all solution but it's not working. 
 "react-native": "0.63.2",
 "@invertase/react-native-apple-authentication": "^2.1.5",

**Comment by konri** [comment]
same here: 
"react-native": "^0.66.4", 
To build android I need to remove @invertase/react-native-apple-authentication library. In iOS it works as a charm.

**Comment by mikehardy** [comment]
So if you use old software that relies on old build toolchains then there is the risk of new dependency versions not working with the obsolete toolchain versions

I recognize react-native 0.66 is only about a year old, but the toolchains it was using were already a bit old when that release branch was cut

react-native 0.63 - I can't believe it even still runs as it is 2 years old :-), but it does I tested it just now.

The problem is the old android toolchains in use there do not seem to handle kotlin 1.7.x+ yet, so what you need is to modify your `android/build.gradle` file to have this in the `ext` block, pinning kotlin at the current most recent 1.6.x version, which is 1.6.21. I tested it and it works.

```groovy
buildscript {
    ext {
        // ... other stuff will be in the block
        kotlinVersion = "1.6.21"  // <-- add this
    }
```

**Comment by zegenerative** [comment]
I am on react-native 0.67.5 with kotlinVersion 1.8 (needed for other dependecy) and it also doesn't work here.
