### ISSUE TITLE
bundle aab Type com.RNAppleAuthentication.AppleAuthenticationAndroidModule$2 is defined multiple times 

### ISSUE THREAD

**Issue by tsansome** [invertase/react-native-apple-authentication#298]
Hi,

On attempting to bundle my app i'm getting this error. IOS is building fine for Apple store but having issues with trying to get my app into google play now because it won't bundle.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/2570105/189508020-41867c99-9023-4594-bb58-3be61ac17a4a.png">

My react versions
<img width="246" alt="image" src="https://user-images.githubusercontent.com/2570105/189508134-f34ce8a4-aa3c-4076-95f0-4d05f0561122.png">

**Comment by mikehardy** [comment]
Hi there!

I must admit, I never understand why people take a text medium (bug reports, code, github) and paste hard to read graphics in there. It's strongly preferred to copy paste the *actual* text, and just enclose it in triple-backticks so people can read. Because your image is really hard to read, and I can't copy paste it in for web searches, so it's unfriendly to maintainers like myself.

Either way, looks like you've included the module twice somehow, maybe with manual linking and then auto-linking, but you haven't provided any evidence to back the hunch or really troubleshoot, so I can't offer more than "examine your gradle files"

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example

If you pull the example here, I think it works? It's on older versions but nothing has changed. I'm on the versions you are using and it works for me so this will be project-specific I think, unless demonstrated otherwise with a clean repro
