### ISSUE TITLE
How to move apple logo to left side away from the text

### ISSUE THREAD

**Issue by mansoorameen** [invertase/react-native-apple-authentication#322]
I couldnt find anything related to this styling in docs. 
Any help is appreciated

**Comment by mikehardy** [comment]
This sort of thing has been asked in the issues before - you basically have two choices:

1- use the provided apple button, accept how it looks
2- make a completely custom button so that it looks the way you like (but be careful that it looks very well done and matches general Apple guidelines or they will reject your app)

I have chosen to do option 2 in my app, but there is no need to provide guidance in our docs on how to make and style an interactive button, as that is a typical task for any react-native developer, so we don't address it
