### ISSUE TITLE
Not working on Simulator with iOS 13.0

### ISSUE THREAD

**Issue by flashman2** [invertase/react-native-apple-authentication#85]
I'm trying to launch app with this module and got stuck with this issue. Module is reporting: "AppleAuth is not supported on the device. Currently Apple Authentication works on iOS devices running iOS 13 or later." I'm launching it on iPhone11 Simulator with iOS 13.0. Xcode version 11.0. SignIn with Apple is enabled in Xcode project. 
I looked at the source codes and saw this:
@"isSupported": @available(iOS 13.0, *) ? @(YES) : @(NO),
I don't know why it's not working. Maybe this is a bug in module. Is there something that should be enabled in Simulator in order to make it work? Do I need to modify iOS settings somehow?
<img width="378" alt="Screen Shot 2020-05-28 at 03 44 21" src="https://user-images.githubusercontent.com/981169/83077238-d22f2680-a098-11ea-97b3-a019b0694f51.png">
<img width="632" alt="Screen Shot 2020-05-28 at 03 45 38" src="https://user-images.githubusercontent.com/981169/83077264-deb37f00-a098-11ea-9448-3996674a311e.png">
<img width="359" alt="Screen Shot 2020-05-28 at 03 44 59" src="https://user-images.githubusercontent.com/981169/83077295-ea9f4100-a098-11ea-8e40-c21e2c41293f.png">
<img width="336" alt="Screen Shot 2020-05-28 at 03 53 18" src="https://user-images.githubusercontent.com/981169/83077317-f12db880-a098-11ea-9680-4d6dafd3b698.png">

**Comment by mikehardy** [comment]
I'm not exactly sure what is wrong with your project config but I want to state very clearly: There is no bug in the module. The module works.

I say that as clearly as possible so that you focus your troubleshooting in the correct spot. Something is wrong with your project or apple config.

You might try `npx react-native-clean-project`. It should work on a simulator (the second time you try) or on a real device. You can also try the example here.

We see these issues from time to time and they are never a problem with the module, so I'm going to close this.

**Comment by Harwood** [comment]
I've seen this as well. Haven't tried `npx react-native-clean-project` but a quick `git clean -qdfx && npm i` did wonders for me.

**Comment by bncvnc** [comment]
I am having issue on my apple login on ipad it is working fine on my phones but when i submit my app to app store for review they just rejects it because if apple login not working don`t know whats wrong with it working on ipad i dont have a ipad so i can not test it and it has already been 15 or more days since i am getting my app rejected on app store with only because of this issue
