### ISSUE TITLE
Where to add the "authorisation callback URL"?

### ISSUE THREAD

**Issue by skizzo** [invertase/react-native-apple-authentication#91]
Hi,
I can't find where in the Apple Developer Console I'm supposed to add the "authorization callback URL" given to me from Firebase:

![WhereToAddAuthCallbackUrl](https://user-images.githubusercontent.com/2892572/84163643-024fcf80-aa72-11ea-8a41-ec18641a7a9a.jpg)

The only thing shown in the dialog for "configuring" the login is this shit:
<img width="669" alt="Screenshot 2020-06-09 at 16 57 45" src="https://user-images.githubusercontent.com/2892572/84164048-6377a300-aa72-11ea-9f65-fcac2c0b671e.png">

Can anybody point me in the right direction please?
Thanks!

**Comment by mikehardy** [comment]
It's pretty poorly documented on Apple's part.
Open apple dev console to the resources list on "identifiers" at the left and "services ids" in the drop-down on the right (tricky!) https://developer.apple.com/account/resources/identifiers/list/serviceId

There you need to add a service id and in that service id you can enable sign in with apple, and in the configure box there you'll see this, where you can put it in

Because developing for the iOS platform is ~~so fun and profitable that they have to force you to use their features or you will be locked out of their monopoly marketplace~~ easy

![Screenshot from 2020-06-09 13-18-28](https://user-images.githubusercontent.com/782704/84185102-1b498800-aa54-11ea-9577-65c1b313beda.png)

**Comment by corepuncher** [comment]
I too am using firebase in a flutter app, along with sign in with apple package. 

I have the capability in xcode, I see the capability checked on developer website, and I followed the above instructions to add the firebase URLs.  

In my app, I do this:

user = await signInWithApple();

Still, in debug, it first prints out my FCM Token, then, on (simulator) screen, it shows a small dialog with "Cancel" or "Settings". If I choose "Settings", my app continues to load and it thinks I cancelled setup as user == null.

The error message in debug window is:

"Sign in with Apple failed: The operation couldn’t be completed. (com.apple.AuthenticationServices.AuthorizationError error 1000.)"

I'm not sure what is left at this point.

**Comment by Haider-Ali-7** [comment]
@corepuncher You need to test Apple sign in on real device.

**Comment by maahd** [comment]
Thanks that is useful. I am getting an error:

An attribute in the provided entity has invalid value

An App ID with Identifier 'com.xxxx.xxxxxxxx' is not available. Please enter a different string.

xxxx being the actual domain name and xxxxxxxx being the actual app name. Anyone knows what this is about?

In the instructions it says:
We recommend using a reverse-domain name style string (i.e., com.domainname.appname). It cannot contain an asterisk (*).
